module.exports = [
  '<style type="text/css">',
  'body {',
  '  font-family: "Consolas", monospace;',
  '  font-weight: normal;',
  '  font-size: 12px;',
  '  line-height: 16px;',
  '  letter-spacing: 0;',
  '  background-color: #080808;',
  '  color: #d4d4d4;',
  '  text-align: left;',
  '  border-top: 1px solid #121516;',
  '  padding: 10px;',
  '  margin: 0;',
  '  display: flex;',
  '  justify-content: space-around;',
  '}',
  '::-webkit-scrollbar { width: 10px; }',
  '::-webkit-scrollbar-thumb { background: #666; border-radius: 10px; }',
  '::-webkit-scrollbar-track {  background: #222; border-radius: 10px; }',
  '::-webkit-scrollbar-button { background: #666; height: 15px; border-radius: 50%; }',
  '.col { text-align:center; }',
  '.col h2 { display: inline-block; margin-right: 15px; }',
  '.json-pretty { padding: 30px; max-height: 100vh; text-align:left; overflow-y: auto; }',
  '.json-selected { background-color: rgba(139, 191, 228, 0.19999999999999996) }',
  '.json-string { color: #00ccaa; }',
  '.json-key { color: #8caedd; }',
  '.json-boolean { color: #cc9994; }',
  '.json-number { color: #cc9994; }',
  '</style>'
].join('\n');
