const exampleArtists = [{
  id: 0,
  firstName: 'Frederic',
  lastName: 'Chopin',
  pictures: ['chopin.jpg']
}, {
  id: 1,
  firstName: 'Ludwig van',
  lastName: 'Beethoven',
  pictures: ['beethoven.jpg']
}, {
  id: 2,
  firstName: 'Nikolai',
  lastName: 'Rimsky-Korsakov'
}, {
  id: 3,
  firstName: 'Johann',
  lastName: 'Pachelbel',
}, {
  id: 4,
  firstName: 'Wolfgang Amadeus',
  lastName: 'Mozart',
  picture: ['mozart.jpg']
}, {
  id: 5,
  firstName: 'Antonio',
  lastName: 'Vivaldi',
}, {
  id: 6,
  firstName: 'Johann Sebastian',
  lastName: 'Bach',
  picture: ['bach.jpg']
}, {
  id: 7,
  firstName: 'Pyotr Ilyich',
  lastName: 'Tchaikovsky',
  picture: ['tchaikovsky.jpg']
}, {
  id: 8,
  firstName: 'Richard',
  lastName: 'Wagner',
  picture: ['wagner.jpg']
}, {
  id: 9,
  firstName: 'Joseph',
  lastName: 'Haydn',
  picture: ['haydn.jpg']
}, {
  id: 10,
  firstName: 'Robert',
  lastName: 'Schumann',
  picture: ['schumann.jpg']
}, {
  id: 11,
  firstName: 'Felix',
  lastName: 'Mendelssohn',
  picture: ['mendelssohn.jpg']
}, {
  id: 12,
  firstName: 'Antonin',
  lastName: 'Dvorak',
  picture: ['dvorak.jpg']
}, {
  id: 13,
  firstName: 'Franz',
  lastName: 'Liszt',
  picture: ['liszt.jpg']
}, {
  id: 14,
  firstName: 'Igor',
  lastName: 'Stravinsky',
  picture: ['stravinsky.jpg']
}, {
  id: 15,
  firstName: 'Giuseppe',
  lastName: 'Verdi',
  picture: ['verdi.jpg']
}, {
  id: 16,
  firstName: 'Gustav',
  lastName: 'Mahler',
  picture: ['mahler.jpg']
}, {
  id: 17,
  firstName: 'Dmitri',
  lastName: 'Shostakovich',
  picture: ['shostakovich.jpg']
}, {
  id: 18,
  firstName: 'Richard',
  lastName: 'Strauss',
  picture: ['strauss.jpg']
}, {
  id: 19,
  firstName: 'Hector',
  lastName: 'Berlioz',
  picture: ['berlioz.jpg']
}, {
  id: 20,
  firstName: 'Claude',
  lastName: 'Debussy',
  picture: ['debussy.jpg']
}, {
  id: 21,
  firstName: 'Giacomo',
  lastName: 'Puccini',
  picture: ['puccini.jpg']
}, {
  id: 22,
  firstName: 'Giovanni Pierluigi da',
  lastName: 'Palestrina',
  picture: ['palestrina.jpg']
}, {
  id: 23,
  firstName: 'Anton',
  lastName: 'Bruckner',
  picture: ['bruckner.jpg'],
}, {
  id: 24,
  firstName: 'Joseph',
  lastName: 'Brahms',
  picture: ['brahms.jpg'],
}, {
  id: 25,
  firstName: 'Franz',
  lastName: 'Schubert',
  picture: ['schubert.jpg'],
}, {
  id: 26,
  firstName: 'Georg Friedrich',
  lastName: 'Handel',
  picture: ['handel.jpg'],
}];

export default exampleArtists;
